-- ============================================
-- IT Helpdesk - Supabase Setup Script
-- Run this in Supabase SQL Editor
-- ============================================

-- ============================================
-- PART 1: Fix profiles table RLS policies
-- (This fixes the PIN change error)
-- ============================================

-- Allow authenticated users to read all profiles
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Allow all authenticated to read profiles' AND tablename = 'profiles'
  ) THEN
    CREATE POLICY "Allow all authenticated to read profiles" 
    ON profiles FOR SELECT 
    USING (auth.role() = 'authenticated');
  END IF;
END $$;

-- Allow users to update their own profile (PIN change for self)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to update own profile' AND tablename = 'profiles'
  ) THEN
    CREATE POLICY "Allow users to update own profile" 
    ON profiles FOR UPDATE 
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);
  END IF;
END $$;

-- Allow admin to update any profile (Admin PIN reset)
-- NOTE: This requires a 'role' column in profiles table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Allow admin to update any profile' AND tablename = 'profiles'
  ) THEN
    CREATE POLICY "Allow admin to update any profile" 
    ON profiles FOR UPDATE 
    USING (
      EXISTS (
        SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
      )
    );
  END IF;
END $$;


-- ============================================
-- PART 2: Create ticket_history table (Audit Log)
-- ============================================

CREATE TABLE IF NOT EXISTS ticket_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  edited_by UUID REFERENCES profiles(id) ON DELETE CASCADE,
  changes JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on ticket_history
ALTER TABLE ticket_history ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to view history
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Allow all to view history' AND tablename = 'ticket_history'
  ) THEN
    CREATE POLICY "Allow all to view history" 
    ON ticket_history FOR SELECT 
    USING (auth.role() = 'authenticated');
  END IF;
END $$;

-- Allow authenticated users to insert history
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated to insert history' AND tablename = 'ticket_history'
  ) THEN
    CREATE POLICY "Allow authenticated to insert history" 
    ON ticket_history FOR INSERT 
    WITH CHECK (auth.role() = 'authenticated');
  END IF;
END $$;
